/** 展示类组件 */
export { default as Tag } from './Tag.vue'
export { default as CheckableTag } from './CheckableTag.vue'
export { default as Avatar } from './Avatar.vue'
export { default as Badge } from './Badge.vue'
export { default as Empty } from './Empty.vue'
export { default as Progress } from './Progress.vue'
export { default as Timeline } from './Timeline.vue'
export { default as Spin } from './Spin.vue'
export { default as Skeleton } from './Skeleton.vue'
export { default as Statistic } from './Statistic.vue'
export { default as Image } from './Image.vue'
export { default as QRCode } from './QRCode.vue'
export { default as Watermark } from './Watermark.vue'
export { default as Trend } from './Trend.vue'
